
# This is the stages / task to perform in jobs
stages:
  - test
  - build
  - deploy
  - release

# GitLab test ---------------------------------------------------
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
# GitLab test ---------------------------------------------------
# Flat job: registering release to GitLab release management section
release_job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo 'release job'
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: './CHANGELOG.md'
# Flat job: registering release to GitLab release management section